version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2 
    commands:
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - apt-get update && apt-get install -y libpq-dev libzip-dev php-pgsql
  pre_build:
    commands:
      - ./install_dependencies.sh
artifacts:
  files:
    - '**/*'
  name: $(date +%Y-%m-%dT%H:%M:%S).zip
proxy:
  upload-artifacts: yes
  logs: yes
